#################################### TERMS OF USE ###########################################
# The following code is provided for demonstration purpose only, and should not be used      #
# without independent verification. Recorded Future makes no representations or warranties,  #
# express, implied, statutory, or otherwise, regarding any aspect of this code or of the     #
# information it may retrieve, and provides it both strictly “as-is” and without assuming    #
# responsibility for any information it may retrieve. Recorded Future shall not be liable    #
# for, and you assume all risk of using, the foregoing. By using this code, Customer         #
# represents that it is solely responsible for having all necessary licenses, permissions,   #
# rights, and/or consents to connect to third party APIs, and that it is solely responsible  #
# for having all necessary licenses, permissions, rights, and/or consents to any data        #
# accessed from any third party API.                                                         #
##############################################################################################

from enum import Enum


class EntityType(str, Enum):
    """Supported Entity Types by the Entity Match API."""

    ASNumber = 'ASNumber'
    AWSAccessKey = 'AWSAccessKey'
    Aircraft = 'Aircraft'
    Airport = 'Airport'
    AnalystNote = 'AnalystNote'
    Anniversary = 'Anniversary'
    AttackVector = 'AttackVector'
    BankIdentificationNumber = 'BankIdentificationNumber'
    BitcoinAddress = 'BitcoinAddress'
    BusinessIdentifierCode = 'BusinessIdentifierCode'
    Case = 'Case'
    Category = 'Category'
    City = 'City'
    CodeIdentifier = 'CodeIdentifier'
    Commodity = 'Commodity'
    Company = 'Company'
    ContentType = 'ContentType'
    Continent = 'Continent'
    Country = 'Country'
    Currency = 'Currency'
    CurrencyPair = 'CurrencyPair'
    CyberExploitTargetCategory = 'CyberExploitTargetCategory'
    CyberSecurityCategory = 'CyberSecurityCategory'
    CyberThreatActorCategory = 'CyberThreatActorCategory'
    CyberVulnerability = 'CyberVulnerability'
    DEANumber = 'DEANumber'
    Dataset = 'Dataset'
    DetectionRule = 'DetectionRule'
    Document = 'Document'
    EconomicIndicator = 'EconomicIndicator'
    EmailAddress = 'EmailAddress'
    Embassy = 'Embassy'
    Emoji = 'Emoji'
    EntertainmentAwardEvent = 'EntertainmentAwardEvent'
    Entity = 'Entity'
    EntityAlias = 'EntityAlias'
    EntityList = 'EntityList'
    EntityRange = 'EntityRange'
    EntityRelation = 'EntityRelation'
    ExternalIdentifier = 'ExternalIdentifier'
    Facility = 'Facility'
    FaxNumber = 'FaxNumber'
    Feature = 'Feature'
    FileContent = 'FileContent'
    FileName = 'FileName'
    FileNameExtension = 'FileNameExtension'
    FileType = 'FileType'
    GeoBoundingBox = 'GeoBoundingBox'
    GeoEntity = 'GeoEntity'
    Hash = 'Hash'
    HashAlgorithm = 'HashAlgorithm'
    Hashtag = 'Hashtag'
    Holiday = 'Holiday'
    IRCNetwork = 'IRCNetwork'
    Identifier = 'Identifier'
    Image = 'Image'
    IncidentImpactCategory = 'IncidentImpactCategory'
    Industry = 'Industry'
    IndustryTerm = 'IndustryTerm'
    IntegrationApplication = 'IntegrationApplication'
    IntegrationUser = 'IntegrationUser'
    InternetDomainName = 'InternetDomainName'
    IpAddress = 'IpAddress'
    Keyword = 'Keyword'
    Language = 'Language'
    LinkReport = 'LinkReport'
    Logotype = 'Logotype'
    MICR = 'MICR'
    Malware = 'Malware'
    MalwareCategory = 'MalwareCategory'
    MalwareMutex = 'MalwareMutex'
    MalwareSignature = 'MalwareSignature'
    MarketIndex = 'MarketIndex'
    MedicalCondition = 'MedicalCondition'
    MedicalTreatment = 'MedicalTreatment'
    MetaAttribute = 'MetaAttribute'
    MetaType = 'MetaType'
    MilitaryBase = 'MilitaryBase'
    MilitaryExercise = 'MilitaryExercise'
    MitreAttackIdentifier = 'MitreAttackIdentifier'
    Movie = 'Movie'
    MusicAlbum = 'MusicAlbum'
    MusicGroup = 'MusicGroup'
    Nationality = 'Nationality'
    NaturalFeature = 'NaturalFeature'
    Neighborhood = 'Neighborhood'
    NetworkPort = 'NetworkPort'
    NetworkProtocol = 'NetworkProtocol'
    NumericIdentifier = 'NumericIdentifier'
    OperatingSystem = 'OperatingSystem'
    Operation = 'Operation'
    OrgEntity = 'OrgEntity'
    Organization = 'Organization'
    PaymentCardNumber = 'PaymentCardNumber'
    Person = 'Person'
    PhoneNumber = 'PhoneNumber'
    Port = 'Port'
    Position = 'Position'
    ProductIdentifier = 'ProductIdentifier'
    ProductModule = 'ProductModule'
    ProductModuleAddon = 'ProductModuleAddon'
    ProductVersion = 'ProductVersion'
    Product = 'Product'
    ProgrammingLanguage = 'ProgrammingLanguage'
    ProvinceOrState = 'ProvinceOrState'
    PublishedMedium = 'PublishedMedium'
    RadioProgram = 'RadioProgram'
    RadioStation = 'RadioStation'
    Region = 'Region'
    Religion = 'Religion'
    ReportEntity = 'ReportEntity'
    ReportingEntity = 'ReportingEntity'
    RiskContext = 'RiskContext'
    RiskRule = 'RiskRule'
    Sector = 'Sector'
    SnortDetectionRule = 'SnortDetectionRule'
    SocialSecurityNumber = 'SocialSecurityNumber'
    Source = 'Source'
    SourceMediaType = 'SourceMediaType'
    SportsEvent = 'SportsEvent'
    SportsGame = 'SportsGame'
    SportsLeague = 'SportsLeague'
    TVShow = 'TVShow'
    TVStation = 'TVStation'
    Task = 'Task'
    Technology = 'Technology'
    TechnologyArea = 'TechnologyArea'
    Thread = 'Thread'
    Topic = 'Topic'
    UPSTrackingNumber = 'UPSTrackingNumber'
    URL = 'URL'
    USPSTrackingNumber = 'USPSTrackingNumber'
    UUID = 'UUID'
    UseCaseConfiguration = 'UseCaseConfiguration'
    UseCaseReport = 'UseCaseReport'
    User = 'User'
    UserEnterprise = 'UserEnterprise'
    UserEntity = 'UserEntity'
    UserGroup = 'UserGroup'
    UserLabel = 'UserLabel'
    UserModuleGroup = 'UserModuleGroup'
    UserModuleRoleGroup = 'UserModuleRoleGroup'
    UserOrganization = 'UserOrganization'
    UserRole = 'UserRole'
    Username = 'Username'
    Vessel = 'Vessel'
    WebMoneyID = 'WebMoneyID'
    WinRegKey = 'WinRegKey'
    YaraDetectionRule = 'YaraDetectionRule'
