name: Unittests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  checks: write
  pull-requests: write


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJSON(vars.PYTHON_SUPPORTED_VERSIONS) }}

    name: "Python ${{ matrix.python_version }}"

    runs-on: ubuntu-latest

    env:
      RF_TOKEN: ${{ secrets.RF_TOKEN || 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' }}
      MIN_COVERAGE: 84
      TERM: dumb
    
    steps:
      - uses: actions/checkout@v6

      - name: Cache apt archives
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-tshark-${{ runner.os }}-v1

      - name: Install TShark
        run: |
          if ! command -v tshark >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y tshark
          fi

      - uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ matrix.python_version }}

      - name: Set up venv
        run: uv sync 

      - name: Run Unittests
        run: |
          uv run -p ${{ matrix.python_version}} pytest \
              --cov \
              --cov-fail-under=${{ env.MIN_COVERAGE }} \
              --random-order-bucket=module \
              -v 
