name: Unittests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  checks: write
  pull-requests: write


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJSON(vars.PYTHON_SUPPORTED_VERSIONS) }}

    name: "Python ${{ matrix.python_version }}"

    runs-on: ubuntu-latest

    env:
      RF_TOKEN: ${{ secrets.RF_TOKEN || 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' }}
      MIN_COVERAGE: 84
    
    steps:
      - name: Install TShark 4.4.10
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:wireshark-dev/stable
          sudo apt-get update
          sudo apt-get install -y tshark

      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ matrix.python_version }}

      - name: Set up venv
        run: uv sync 

      - name: Run Unittests
        run: |
          uv run -p ${{ matrix.python_version}} pytest \
              --cov \
              --cov-fail-under=${{ env.MIN_COVERAGE }} \
              --random-order-bucket=module \
              -v 
